import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
const homeStart = s.indexOf("export default function Home");
if (!s.includes("calendarMonth")) s = s.replace('  const [active, setActive] = useState("Visão geral");', '  const [active, setActive] = useState("Visão geral");\n  const [calendarMonth, setCalendarMonth] = useState(() => localStorage.getItem("worktrack-calendar-month") || new Date().toISOString().slice(0, 7));\n  const [profileName, setProfileName] = useState(() => localStorage.getItem("worktrack-profile-name") || "Meu WorkTrack");\n  const [themeMode, setThemeMode] = useState(() => localStorage.getItem("worktrack-theme") || "paper");\n  const [paymentStatusFilter, setPaymentStatusFilter] = useState("Todos");\n  const [paymentFrom, setPaymentFrom] = useState("");\n  const [paymentTo, setPaymentTo] = useState("");');
const homeReturn = s.indexOf('  return <div className="app-shell">', homeStart);
const derived = [
'  const calendarDate = new Date(`${calendarMonth}-15T12:00:00`);',
'  const calendarMonthLabel = new Intl.DateTimeFormat("pt-PT", { month: "long", year: "numeric" }).format(calendarDate);',
'  const calendarCells = (() => { const first = new Date(calendarDate.getFullYear(), calendarDate.getMonth(), 1); const total = new Date(calendarDate.getFullYear(), calendarDate.getMonth() + 1, 0).getDate(); const offset = (first.getDay() + 6) % 7; return [...Array(offset).fill(null), ...Array.from({ length: total }, (_, i) => String(i + 1).padStart(2, "0"))]; })();',
'  const paymentJobs = jobs.filter(j => (paymentStatusFilter === "Todos" || j.status === paymentStatusFilter) && (!paymentFrom || j.date >= paymentFrom) && (!paymentTo || j.date <= paymentTo));',
'  function moveCalendarMonth(delta: number) { const next = new Date(calendarDate.getFullYear(), calendarDate.getMonth() + delta, 1); const value = next.toISOString().slice(0, 7); setCalendarMonth(value); localStorage.setItem("worktrack-calendar-month", value); }',
].join("\n") + "\n";
if (!s.includes("const calendarDate")) s = s.slice(0, homeReturn) + derived + s.slice(homeReturn);
s = s.replace('<div className="page-wrap">', '<div key={active} className={`page-wrap section-transition theme-${themeMode}`}>');
const introEnd = '</section><section className="chart-suite">';
const calendar = '<section className="calendar-panel panel"><div className="calendar-heading"><div><p className="eyebrow">AGENDA DO MÊS</p><h2>Calendário de {calendarMonthLabel}</h2></div><div className="calendar-actions"><button aria-label="Mês anterior" onClick={() => moveCalendarMonth(-1)}><ChevronLeft size={15} /></button><button className="calendar-today" onClick={() => { const value = new Date().toISOString().slice(0, 7); setCalendarMonth(value); localStorage.setItem("worktrack-calendar-month", value); }}>Mês atual</button><button aria-label="Próximo mês" onClick={() => moveCalendarMonth(1)}><ChevronRight size={15} /></button></div></div><div className="calendar-weekdays">{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarCells.map((day, index) => <span key={index} className={day && jobs.some(j => j.date === `${calendarMonth}-${day}`) ? "has-work" : ""}>{day || ""}</span>)}</div></section>';
if (!s.includes('className="calendar-panel panel"')) s = s.replace(introEnd, `</section>${calendar}<section className="chart-suite">`);
const settingsOld = '<div className="settings-content"><p>Os seus dados ficam armazenados localmente neste navegador.</p><button className="clear-filters visible" onClick={() => { if (window.confirm("Apagar todos os trabalhos e metas salvos neste navegador?")) { localStorage.removeItem("worktrack-jobs"); localStorage.removeItem("worktrack-goals"); window.location.reload(); } }}>Apagar dados locais</button></div>';
const settingsNew = '<div className="settings-content"><div className="settings-form"><label>Nome do perfil<input value={profileName} onChange={e => { setProfileName(e.target.value); localStorage.setItem("worktrack-profile-name", e.target.value); }} placeholder="Como deseja identificar seu WorkTrack?" /></label><label>Tema visual<select value={themeMode} onChange={e => { setThemeMode(e.target.value); localStorage.setItem("worktrack-theme", e.target.value); }}><option value="paper">Papel editorial</option><option value="night">Navy noturno</option><option value="sand">Areia quente</option></select></label></div><p>Os seus dados ficam armazenados localmente neste navegador.</p><button className="clear-filters visible" onClick={() => { if (window.confirm("Apagar todos os trabalhos e metas salvos neste navegador?")) { localStorage.removeItem("worktrack-jobs"); localStorage.removeItem("worktrack-goals"); window.location.reload(); } }}>Apagar dados locais</button></div>';
s = s.replace(settingsOld, settingsNew);
const paymentNote = '<p className="analysis-note">Acompanhe aqui os valores pagos e pendentes do período selecionado.</p>';
const paymentNew = '<div className="payment-filters"><select value={paymentStatusFilter} onChange={e => setPaymentStatusFilter(e.target.value)}><option>Todos</option><option>Pago</option><option>Pendente</option></select><label>De<input type="date" value={paymentFrom} onChange={e => setPaymentFrom(e.target.value)} /></label><label>Até<input type="date" value={paymentTo} onChange={e => setPaymentTo(e.target.value)} /></label><button className="clear-filters visible" onClick={() => { setPaymentStatusFilter("Todos"); setPaymentFrom(""); setPaymentTo(""); }}>Limpar</button></div><div className="payment-filter-results">{paymentJobs.length} {paymentJobs.length === 1 ? "trabalho encontrado" : "trabalhos encontrados"}</div>';
s = s.replace(paymentNote, `${paymentNew}${paymentNote}`);
fs.writeFileSync(path, s);
