import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
if (!s.includes('selectedMonthSlice')) s = s.replace('  const [selectedSlice, setSelectedSlice] = useState("");', '  const [selectedSlice, setSelectedSlice] = useState("");\n  const [selectedMonthSlice, setSelectedMonthSlice] = useState("");\n  const [hoveredMonthSlice, setHoveredMonthSlice] = useState("");');
const marker = '  return (';
const helper = `  const monthlyChartData = monthWeekRows.map(row => ({ label: row.label, ganho: row.gross, horas: row.hours, despesas: row.expense, liquido: row.net }));
  const monthlyTooltip = ({ active, payload }: any) => { if (!active || !payload?.length) return null; const item = payload[0].payload; return <div className="chart-tooltip"><b>{item.label}</b><span>Bruto: {eur(item.ganho)}</span><span>Despesas: {eur(item.despesas)}</span><span>Líquido: {eur(item.liquido)}</span><span>Horas: {item.horas.toFixed(1).replace(".", ",")}h</span></div>; };
`;
if (!s.includes('const monthlyChartData')) { const i = s.indexOf(marker); s = s.slice(0, i) + helper + s.slice(i); }
const start = s.indexOf('<div className="monthly-goals">');
const end = s.indexOf('<div className="analysis-table-wrap">', start);
if (start < 0 || end < 0) throw new Error('monthly section not found');
const colors = '["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"]';
const replacement = `<div className="monthly-goals"><div><p className="eyebrow">METAS DO MÊS</p><h3>Seu avanço em perspectiva</h3><button className="text-link" onClick={() => setEditingGoals(true)}>Editar metas <ArrowUpRight size={14} /></button></div><Goal label="Meta de ganhos" value={monthMetrics.gross} target={monthGoal} suffix="€" color="green" /><Goal label="Meta de horas" value={monthMetrics.hours} target={monthHourGoal} suffix="h" color="navy" /></div><div className="monthly-interactive"><div className="monthly-chart-card"><div className="monthly-chart-head"><span>Ganhos por semana</span><small>hover para detalhar</small></div><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={monthlyChartData} dataKey="ganho" nameKey="label" innerRadius={48} outerRadius={70} paddingAngle={2} onMouseEnter={(_, index) => setHoveredMonthSlice(monthlyChartData[index]?.label || "")} onMouseLeave={() => setHoveredMonthSlice("")} onClick={(_, index) => setSelectedMonthSlice(monthlyChartData[index]?.label || "")}><Cell /></Pie><Tooltip content={monthlyTooltip} /></PieChart></ResponsiveContainer><div className="monthly-legend">{monthlyChartData.map((item, index) => <button type="button" className={(hoveredMonthSlice || selectedMonthSlice) === item.label ? "active" : ""} onMouseEnter={() => setHoveredMonthSlice(item.label)} onMouseLeave={() => setHoveredMonthSlice("")} onClick={() => setSelectedMonthSlice(item.label)} key={item.label}><i style={{ background: ${colors}[index % ${colors}.length] }} /><span><b>{item.label}</b><small>{eur(item.ganho)} · {((item.ganho / (monthMetrics?.gross || 1)) * 100).toFixed(0)}% · líquido {eur(item.liquido)}</small></span></button>)}</div></div><div className="monthly-chart-card"><div className="monthly-chart-head"><span>Horas por semana</span><small>despesas no tooltip</small></div><ResponsiveContainer width="100%" height={190}><PieChart><Pie data={monthlyChartData} dataKey="horas" nameKey="label" innerRadius={48} outerRadius={70} paddingAngle={2} onMouseEnter={(_, index) => setHoveredMonthSlice(monthlyChartData[index]?.label || "")} onMouseLeave={() => setHoveredMonthSlice("")} onClick={(_, index) => setSelectedMonthSlice(monthlyChartData[index]?.label || "")}>{monthlyChartData.map((item, index) => <Cell key={item.label} fill={${colors}[index % ${colors}.length]} opacity={(hoveredMonthSlice || selectedMonthSlice) && (hoveredMonthSlice || selectedMonthSlice) !== item.label ? 0.3 : 1} stroke={(hoveredMonthSlice || selectedMonthSlice) === item.label ? "#b78643" : "none"} strokeWidth={(hoveredMonthSlice || selectedMonthSlice) === item.label ? 3 : 0} />)}</Pie><Tooltip content={monthlyTooltip} /></PieChart></ResponsiveContainer></div></div>`;
s = s.slice(0, start) + replacement + s.slice(end);
fs.writeFileSync(path, s);
