import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
const start = s.indexOf('  const monthlyChartData =');
const returnAfterHome = s.indexOf('  return (', s.indexOf('export default function Home'));
if (start < 0 || returnAfterHome < 0) throw new Error('monthly scope markers not found');
const end = s.indexOf('  return (', start);
const block = s.slice(start, end);
s = s.slice(0, start) + s.slice(end);
const newReturn = s.indexOf('  return (', s.indexOf('export default function Home'));
s = s.slice(0, newReturn) + block + s.slice(newReturn);
s = s.replace('<Pie data={monthlyChartData} dataKey="ganho" nameKey="label" innerRadius={48} outerRadius={70} paddingAngle={2} onMouseEnter={(_, index) => setHoveredMonthSlice(monthlyChartData[index]?.label || "")} onMouseLeave={() => setHoveredMonthSlice("")} onClick={(_, index) => setSelectedMonthSlice(monthlyChartData[index]?.label || "")}><Cell /></Pie>', '<Pie data={monthlyChartData} dataKey="ganho" nameKey="label" innerRadius={48} outerRadius={70} paddingAngle={2} onMouseEnter={(_, index) => setHoveredMonthSlice(monthlyChartData[index]?.label || "")} onMouseLeave={() => setHoveredMonthSlice("")} onClick={(_, index) => setSelectedMonthSlice(monthlyChartData[index]?.label || "")}>{monthlyChartData.map((item, index) => <Cell key={item.label} fill={["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"][index % 7]} opacity={(hoveredMonthSlice || selectedMonthSlice) && (hoveredMonthSlice || selectedMonthSlice) !== item.label ? 0.3 : 1} stroke={(hoveredMonthSlice || selectedMonthSlice) === item.label ? "#b78643" : "none"} strokeWidth={(hoveredMonthSlice || selectedMonthSlice) === item.label ? 3 : 0} />)}</Pie>');
fs.writeFileSync(path, s);
