import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
if (!s.includes('calendar-metrics')) {
  const old = /<section className="calendar-panel panel">[\s\S]*?<\/section><section className="chart-suite">/;
  const fresh = '<section className="calendar-panel panel"><div className="calendar-top"><div><p className="eyebrow">AGENDA DO MÊS</p><h2>{calendarMonthLabel}</h2><p className="calendar-subtitle">Planeje e acompanhe os dias em que houve trabalho.</p></div><div className="calendar-actions"><button type="button" aria-label="Mês anterior" onClick={() => moveCalendarMonth(-1)}><ChevronLeft size={16} /></button><button type="button" className="calendar-today" onClick={() => { const value = new Date().toISOString().slice(0, 7); setCalendarMonth(value); localStorage.setItem("worktrack-calendar-month", value); }}>Hoje</button><button type="button" aria-label="Próximo mês" onClick={() => moveCalendarMonth(1)}><ChevronRight size={16} /></button></div></div><div className="calendar-metrics"><span><b>{jobs.filter(j => j.date.startsWith(calendarMonth)).length}</b> trabalhos</span><span><b>{jobs.filter(j => j.date.startsWith(calendarMonth)).reduce((sum, j) => sum + hoursFor(j), 0).toFixed(1).replace(".", ",")}h</b> registradas</span><span><b>{eur(jobs.filter(j => j.date.startsWith(calendarMonth)).reduce((sum, j) => sum + j.rate * hoursFor(j), 0))}</b> bruto</span></div><div className="calendar-weekdays">{["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarCells.map((day, index) => { const fullDate = day ? `${calendarMonth}-${day}` : ""; const hasWork = day && jobs.some(j => j.date === fullDate); const isToday = fullDate === new Date().toISOString().slice(0, 10); return <button type="button" key={index} disabled={!day} className={`${hasWork ? "has-work" : ""} ${isToday ? "is-today" : ""}`} onClick={() => { if (day) { setFilterDate(fullDate); setActive("Trabalhos"); requestAnimationFrame(() => document.querySelector(".jobs-panel")?.scrollIntoView({ behavior: "smooth", block: "start" })); } }}>{day || ""}{hasWork && <i aria-label="Dia com trabalho" />}</button>; })}</div><div className="calendar-legend"><span><i className="today-dot" /> Hoje</span><span><i className="work-dot" /> Com trabalho</span></div></section><section className="chart-suite">';
  s = s.replace(old, fresh);
}
fs.writeFileSync(path, s);
