import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
s = s.replace('  const [selectedClient, setSelectedClient] = useState("");', '  const [selectedClient, setSelectedClient] = useState("");\n  const [selectedSlice, setSelectedSlice] = useState("");\n  const [labelMode, setLabelMode] = useState<"internal" | "legend">("internal");');
s = s.replaceAll('setDistributionMode(e.target.value as "day" | "client"); setSelectedClient(""); setFilterClient("Todos");', 'setDistributionMode(e.target.value as "day" | "client"); setSelectedClient(""); setSelectedSlice(""); setFilterClient("Todos");');
s = s.replaceAll('setSelectedClient(client); setFilterClient(client); setFilterDate(""); setActive("Trabalhos");', 'setSelectedClient(client); setSelectedSlice(client); setFilterClient(client); setFilterDate(""); setActive("Trabalhos");');
s = s.replaceAll('setSelectedClient(""); setFilterClient("Todos"); setFilterDate(date); setActive("Trabalhos");', 'setSelectedClient(""); setSelectedSlice(item?.label || ""); setFilterClient("Todos"); setFilterDate(date); setActive("Trabalhos");');
s = s.replaceAll('setSelectedClient(""); setFilterClient("Todos"); }}>Cliente:', 'setSelectedClient(""); setSelectedSlice(""); setFilterClient("Todos"); }}>Cliente:');
s = s.replace('setFilterCategory("Todos"); setSelectedClient(""); }}>Limpar todos', 'setFilterCategory("Todos"); setSelectedClient(""); setSelectedSlice(""); }}>Limpar todos');
s = s.replaceAll('label={({ cx, cy, midAngle, innerRadius, outerRadius, value, percent }) => {', 'label={labelMode === "internal" ? (({ cx, cy, midAngle, innerRadius, outerRadius, value, percent }) => {');
s = s.replaceAll(': null; }}</Pie>', ': null; }) : undefined}</Pie>');
const oldCell = '<Cell key={entry.label} fill={["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"][index % ["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"].length]} />';
const newCell = '<Cell key={entry.label} fill={["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"][index % ["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"].length]} opacity={selectedSlice && selectedSlice !== entry.label ? 0.35 : 1} stroke={selectedSlice === entry.label ? "#b78643" : "none"} strokeWidth={selectedSlice === entry.label ? 3 : 0} />';
s = s.replaceAll(oldCell, newCell);
s = s.replace('<select value={distributionMode} onChange={e => { setDistributionMode(e.target.value as "day" | "client"); setSelectedClient(""); setSelectedSlice(""); setFilterClient("Todos"); }}><option value="day">Dia</option><option value="client">Cliente</option></select>', '<select value={distributionMode} onChange={e => { setDistributionMode(e.target.value as "day" | "client"); setSelectedClient(""); setSelectedSlice(""); setFilterClient("Todos"); }}><option value="day">Dia</option><option value="client">Cliente</option></select><select value={labelMode} onChange={e => setLabelMode(e.target.value as "internal" | "legend")}><option value="internal">Rótulos internos</option><option value="legend">Legenda detalhada</option></select>');
s = s.replaceAll('<div className="pie-legend">{distributionData.map', '<div className={labelMode === "legend" ? "pie-legend detailed" : "pie-legend"}>{distributionData.map');
s = s.replaceAll('</span>)}</div></div><div className="panel mini-chart">', '</span>)}</div></div><div className="panel mini-chart">');
fs.writeFileSync(path, s);
