import fs from "node:fs";
const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let s = fs.readFileSync(path, "utf8");
s = s.replace('const [labelMode, setLabelMode] = useState<"internal" | "legend">("internal");', 'const [labelMode, setLabelMode] = useState<"internal" | "legend">("legend");');
const money = 'label={labelMode === "internal" ? (props => renderPieLabel(props, "money")) : undefined}';
const hours = 'label={labelMode === "internal" ? (props => renderPieLabel(props, "hours")) : undefined}';
const simpleMoney = 'label={labelMode === "internal" ? (({ value, percent }) => percent >= 0.08 ? `${eur(Number(value))} · ${(percent * 100).toFixed(0)}%` : "") : undefined}';
const simpleHours = 'label={labelMode === "internal" ? (({ value, percent }) => percent >= 0.08 ? `${Number(value).toFixed(1).replace(".", ",")}h · ${(percent * 100).toFixed(0)}%` : "") : undefined}';
s = s.replace(money, simpleMoney);
s = s.replace(hours, simpleHours);
s = s.replace(money, simpleMoney);
fs.writeFileSync(path, s);
