import fs from "node:fs";

const path = "/home/ubuntu/worktrack/client/src/pages/Home.tsx";
let source = fs.readFileSync(path, "utf8");
source = source.replace(
  'import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";',
  'import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";'
);
const palette = `["#17324d", "#76a98d", "#d99857", "#b8c9c0", "#6e8790", "#c6a56a", "#294963"]`;
const pie = (key, label) => `<ResponsiveContainer width="100%" height={210}><PieChart><Pie data={chartData} dataKey="${key}" nameKey="day" cx="50%" cy="50%" innerRadius={52} outerRadius={78} paddingAngle={2} labelLine={false} label={({ name, percent }) => percent > 0 ? \`${'${name}'} \${(percent * 100).toFixed(0)}%\` : ""}>{chartData.map((entry, index) => <Cell key={entry.day} fill={${palette}[index % ${palette}.length]} />)}</Pie><Tooltip contentStyle={{ border: "1px solid #e4ded2", borderRadius: 8, background: "#fffdf8" }} formatter={(value) => [${key === 'ganho' ? 'eur(Number(value))' : key === 'horas' ? '`' + '${value}h' + '`' : 'eur(Number(value))'}, "${label}"]} /></PieChart></ResponsiveContainer>`;
const replacement = `<section className="chart-suite"><div className="panel mini-chart"><div className="panel-heading"><div><p className="eyebrow">DISTRIBUIÇÃO</p><h2>Ganhos por dia</h2></div><span className="chart-caption">bruto</span></div>${pie('ganho', 'Ganho')}<div className="pie-legend">{chartData.map((item, index) => <span key={item.day}><i style={{ background: ${palette}[index % ${palette}.length] }} />{item.day}</span>)}</div></div><div className="panel mini-chart"><div className="panel-heading"><div><p className="eyebrow">DISTRIBUIÇÃO</p><h2>Horas por dia</h2></div><span className="chart-caption">tempo</span></div>${pie('horas', 'Horas')}<div className="pie-legend">{chartData.map((item, index) => <span key={item.day}><i style={{ background: ${palette}[index % ${palette}.length] }} />{item.day}</span>)}</div></div><div className="panel mini-chart"><div className="panel-heading"><div><p className="eyebrow">DISTRIBUIÇÃO</p><h2>Valor / hora</h2></div><span className="chart-caption">produtividade</span></div>${pie('valor', '€/hora')}<div className="pie-legend">{chartData.map((item, index) => <span key={item.day}><i style={{ background: ${palette}[index % ${palette}.length] }} />{item.day}</span>)}</div></div></section>`;
source = source.replace(/      <section className="chart-suite">[\s\S]*?<\/section>\n      \{\(active === "Semana"/, `      ${replacement}\n      {(active === "Semana"`);
source = source.replace('<footer className="site-footer"><span>Projeto por <a href="https://www.instagram.com/_7ragnar/" target="_blank" rel="noreferrer">x7rG ENTERPRISE</a></span></footer>', '<footer className="site-footer"><span>© 2026 WorkTrack. Todos os direitos reservados.</span><span>Projeto por <a href="https://www.instagram.com/_7ragnar/" target="_blank" rel="noreferrer">x7rG ENTERPRISE</a></span></footer>');
fs.writeFileSync(path, source);
